# Generated by Django 4.1.1 on 2022-09-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=255)),
                ('expiration', models.DateTimeField(verbose_name='date of expiration')),
                ('access_path', models.CharField(max_length=255)),
            ],
        ),
    ]
