# Generated by Django 4.1.1 on 2022-11-01 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitvpn', '0002_btcpay_wgman_alter_client_expiration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='expiration',
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name='wgman',
            table='wireguard',
        ),
    ]
