# Generated by Django 4.1.1 on 2022-12-04 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitvpn', '0003_alter_client_expiration_alter_wgman_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='access_path',
        ),
        migrations.AddField(
            model_name='client',
            name='public_key',
            field=models.CharField(default=datetime.datetime(2022, 12, 4, 0, 38, 51, 445001, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
    ]
