# Generated by Django 4.1.1 on 2022-12-04 01:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bitvpn', '0004_remove_client_access_path_client_public_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='out_interface',
            field=models.CharField(default=datetime.datetime(2022, 12, 4, 1, 20, 35, 31719, tzinfo=datetime.timezone.utc), max_length=10),
            preserve_default=False,
        ),
    ]
